Lesson2
LudmilaZhuleha/if-html pull request #1
Opened 2022-02-22 20:16 UTC by LudmilaZhuleha

2022-02-22 22:08 UTC, Marinarium requested changes

2022-02-22 22:08 UTC, Marinarium commented on about/index.html
> +<html lang="en">
It's better to use lang="ru" here, because the current page is in Russian. This is for seo, accessibility and etc

2022-02-22 22:08 UTC, Marinarium commented on about/index.html
> +    по ее способности лазать по деревьям,<br> она проживет всю жизнь, считая себя дурой." <sub>/А.Эйнштейн/</sub></em>
`<sub>/А.Эйнштейн/</sub>` I recommend to use [`<cite>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/blockquote) here.
With` <blockquote>` you can use the `<cite>` tag, which is usually placed inside.

2022-02-23 08:20 UTC, LudmilaZhuleha commented on about/index.html
> +    по ее способности лазать по деревьям,<br> она проживет всю жизнь, считая себя дурой." <sub>/А.Эйнштейн/</sub></em>
Following recommendations, adjusted lang="ru" and replaced sub for cite tag.

2022-02-23 09:36 UTC, merged